name: expense_manager
description: A comprehensive expense management Flutter application with cross-platform support, voice input, AI categorization, and data visualization capabilities.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # Data Management
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0

  # File Operations
  csv: ^6.0.0
  excel: ^4.0.6
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  # UI and Visualization
  fl_chart: ^0.69.0

  # Voice and Input
  speech_to_text: ^7.0.0

  # Network and AI
  http: ^1.2.2
  google_generative_ai: ^0.4.6

  # System Integration
  permission_handler: ^11.3.1

  # Additional utilities mentioned in the code
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - web/icons/
    - web/
  
  # App icons are defined in platform-specific directories